package com.netflix.simianarmy.basic.chaos;

import com.netflix.simianarmy.chaos.ChaosCrawler.InstanceGroup;

/**
 * The Class CloudFormationChaosMonkey. Strips out the random string generated by the CloudFormation api in
 * the instance group name of the ASG we want to kill instances on
 */
public class CloudFormationChaosMonkey extends BasicChaosMonkey {

    /**
     * Instantiates a new cloud formation chaos monkey.
     * @param ctx
     *            the ctx
     */
    public CloudFormationChaosMonkey(Context ctx) {
        super(ctx);
    }

    /**
     * {@inheritDoc}
     * @param group
     * @return
     */
    @Override
    protected boolean isGroupEnabled(InstanceGroup group) {
        InstanceGroup noSuffixGroup = noSuffixInstanceGroup(group);
        return super.isGroupEnabled(noSuffixGroup);
    }

    /**
     * {@inheritDoc}
     * @param group
     * @return
     */
    @Override
    protected boolean isMaxTerminationCountExceeded(InstanceGroup group) {
        InstanceGroup noSuffixGroup = noSuffixInstanceGroup(group);
        return super.isMaxTerminationCountExceeded(noSuffixGroup);
    }

    /**
     * {@inheritDoc}
     * @param group
     * @return
     */
    @Override
    protected double getEffectiveProbability(InstanceGroup group) {
        InstanceGroup noSuffixGroup = noSuffixInstanceGroup(group);
        if (!super.isGroupEnabled(noSuffixGroup)) {
            return 0;
        }
        return getEffectiveProbabilityFromCfg(noSuffixGroup);
    }

    /**
     * Return a copy of the instance group removing the randomly generated suffix from
     * its name.
     *
     * @param group
     * @return InstanceGroup
     */
    public InstanceGroup noSuffixInstanceGroup(InstanceGroup group) {
        String newName = group.name().replaceAll("(-)([^-]*$)", "");
        InstanceGroup noSuffixGroup = group.copyAs(newName);
        return noSuffixGroup;
    }
}
